### ISSUE TITLE
PNG transparency is shown as white

### ISSUE THREAD

**Issue by tumingche** [sirxemic/jquery.ripples#17]
Thank you for developing this great feature. I tried to use PNG as the background image, but it ignores the transparency and is shown as white. I tried to add rgba() and opacity in CSS to get rid of the white, but it still doesn't work. Any idea for solving this problem?

**Comment by sirxemic** [comment]
I have no clue why transparency is showing up as white. I experimented a bit and 98% transparency seems to render just fine. So for a temporary workaround maybe replace all 100% transparent pixels to 98% transparent pixels?

I'll investigate this in the meantime.

**Comment by sirxemic** [comment]
I think I just fixed this with commit b9f200ec6bc9845796d6cf8574b68a633cd8d1fd - can you check if it's fixed for you too?

**Comment by tumingche** [comment]
Thank you so much for your prompt reply! The problem is solved, and the PNG
files are shown perfectly with transparency. Thank you again for your
amazing work!


Ming

2015-09-03 14:57 GMT-04:00 Pim Schreurs <notifications@github.com>:

**Comment by sirxemic** [comment]
You're welcome! :D

**Comment by yeesunday** [comment]
Hi guys, i just met the same question. And i had upgrade the newest version, but the problem is still unsolved. Would you give me some tips?
![image](https://cloud.githubusercontent.com/assets/1524720/9975049/1b8c2ffe-5edf-11e5-9ae0-0b76698cf6df.png)
